### PR TITLE
Update to cddlib_jll@0.94.14

### LINKED ISSUE #65: SegFault for BlockElimination
I encountered Segmentation Fault when using BlockElimination function. The minimum test code is as followed:
```
using Polyhedra, CDDLib
A=[-0.5458700320410754 -0.43028245741634163 -0.32949085078374596 -2.0178905562651726 1.0 0.0 0.0; -0.001696359345425646 -0.5944052771561518 -0.14259145370038157 -0.5715464802979783 0.0 1.0 0.0; 0.11176371186473642 0.16920950931092318 -0.6603345932930139 -0.11228115664803578 0.0 0.0 1.0; 0.5458700320410754 0.43028245741634163 0.32949085078374596 2.0178905562651726 -1.0 0.0 0.0; 0.001696359345425646 0.5944052771561518 0.14259145370038157 0.5715464802979783 0.0 -1.0 0.0; -0.11176371186473642 -0.16920950931092318 0.6603345932930139 0.11228115664803578 0.0 0.0 -1.0; -1.0 0.10091143255328394 3.4102811211934987 -6.813065334385856 0.0 0.0 0.0; 1.0 -0.8932312066317769 0.7730763460460294 2.524023981062126 0.0 0.0 0.0; 1.0 -0.0930882189983393 1.7475328342666678 4.495570410302662 0.0 0.0 0.0; -1.0 -0.05182954771533831 -1.1189515717142475 -3.9532525226843815 0.0 0.0 0.0; 1.0 4.239841226638941 -8.774257911319019 -2.2499336877985545 0.0 0.0 0.0; -1.0 1.0414219678515158 1.033883503426593 -0.9840648095304564 0.0 0.0 0.0; 1.0 -0.001284573155440541 -1.6845061382720732 -1.0153065939984884 0.0 0.0 0.0; 1.0 -4.299428761845123 -3.940453969462597 6.702373679526568 0.0 0.0 0.0; -1.0 0.0 0.0 0.0 0.0 0.0 0.0; 0.0 1.0 0.0 0.0 0.0 0.0 0.0]
b=[0.3653256599471767, 0.4574210313524346, 0.35534066564751254, -0.3653256599471767, -0.4574210313524346, -0.35534066564751254, -2.9769531018983972, 0.8613646098710365, 3.3649667529429204, -2.093853811646953, 8.893608931702863, 0.7565246179371888, 1.433621499051063, -3.9487728883626625, -1.0, 2.0]
poly_in = polyhedron(hrep(A,b), CDDLib.Library(:float))
poly_out = eliminate(poly_in, collect(1:4), BlockElimination())
```

I am using Julia v1.4.2 and Ubuntu 18.04. Further package details are as followed:
```
  [6e4b80f9] BenchmarkTools v0.5.0
  [3391f64e] CDDLib v0.6.3
  [5789e2e9] FileIO v1.4.5
  [587475ba] Flux v0.11.1
  [60bf3e95] GLPK v0.13.0
  [033835bb] JLD2 v0.3.1
  [682c06a0] JSON v0.21.1
  [4076af6c] JuMP v0.21.5
  [b4f0291d] LazySets v1.37.14
  [23992714] MAT v0.9.2
  [15e1cf62] NPZ v0.4.0
  [91a5bcdd] Plots v1.6.12
  [67491407] Polyhedra v0.6.11
  [d330b81b] PyPlot v2.9.0
  [9f7883ad] Tracker v0.2.13
  [37e2e46d] LinearAlgebra
```

Any suggestion on this? Thanks.

### PR DESCRIPTION
**Pull request by odow**
- [x] Needs a test, but should close #65

### CODE REVIEW

**Comment by odow** [comment]
@blegat, so this doesn't segfault anymore,  but it does throw:
```Julia
julia> poly_out = eliminate(poly_in, collect(1:4), BlockElimination())
ERROR: ddf_BlockElimination returned a NULL pointer but did not provide any error. Please report this by opening an issue at https://github.com/JuliaPolyhedra/CDDLib.jl.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] myerror
   @ ~/.julia/dev/CDDLib/src/error.jl:31 [inlined]
 [3] macro expansion
   @ ~/.julia/dev/CDDLib/src/ccall.jl:30 [inlined]
 [4] dd_blockelimination(matrix::Ptr{CDDLib.Cdd_MatrixData{Float64}}, delset::Ptr{UInt64})
   @ CDDLib ~/.julia/dev/CDDLib/src/operations.jl:311
 [5] blockelimination(matrix::CDDInequalityMatrix{Float64, Float64}, delset::Vector{Int64})
   @ CDDLib ~/.julia/dev/CDDLib/src/operations.jl:334
 [6] eliminate(p::CDDLib.Polyhedron{Float64}, delset::Vector{Int64}, ::BlockElimination)
   @ CDDLib ~/.julia/dev/CDDLib/src/polyhedron.jl:182
 [7] top-level scope
   @ REPL[10]:1
```

**Comment by blegat** [comment]
Thanks!

**Comment by schillic** [comment]
This change has not been released yet. Is that intentional?

**Comment by blegat** [comment]
Just an oversight, done now ;)

**Pull request merged**
